version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env

  frontend:
    build: ./frontend
    ports:
      - "4000:4000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - PORT=4000
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    command: npm start